service:
  name: sls-appsync-backend-pj

plugins:
  - serverless-appsync-plugin
  - serverless-plugin-additional-stacks
  - serverless-iam-roles-per-function
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  profile: pers_admin
  region: us-west-2
  timeout: 120
  stage: ${opt:stage, "test"}

functions:
  getFileMapDetail1:
    handler: src/handlers/getFileMapDetails.handler
    arn: !GetAtt getFileMapDetail1.Arn
custom:
  base: ${self:service}-${self:provider.stage}
  account: ${file(./config/config.${self:provider.stage}.json):account}
  db: ${file(./config/config.test.json):db}
  cognitoStackName: ${self:custom.base}-cognito
  dynamoDBStackName: ${self:custom.base}-dynamodb

  userPoolId:
    Fn::ImportValue: ${self:custom.cognitoStackName}:${self:provider.stage}:${self:custom.base}-UserPoolId
  # lambdaArn:
  #   arn:
  #       Fn::GetAtt:
  #         - AppSyncLoggingServiceRole
  #         - Arn

  role:
    arn: arn:aws:iam::${self:custom.account.id}:role
    cognito:
      auth:
        name: ${self:custom.base}-auth-CognitoRole
        arn: ${self:custom.role.arn}/${self:custom.role.cognito.auth.name}
      unAuth:
        name: ${self:custom.base}-unAuth-CognitoRole
        arn: ${self:custom.role.arn}/${self:custom.role.cognito.unAuth.name}
    dynamodb:
      name: ${self:custom.base}-DynamoDB-AppSyncServiceRole
      arn: ${self:custom.role.arn}/${self:custom.role.dynamodb.name}
    lambda:
      name: ${self:custom.base}-Lambda-AppSyncServiceRole
      arn: ${self:custom.role.arn}/${self:custom.role.lambda.name}
    logging:
      name: ${self:custom.base}-Logging-AppSyncServiceRole
      arn:
        Fn::GetAtt:
          - AppSyncLoggingServiceRole
          - Arn

  additionalStacks:
    cognitoResources:
      Deploy: Before
      StackName: ${self:custom.cognitoStackName}
      Resources: ${file(./resources/cognito.yml)}
      Outputs: ${file(./resources/cognito-outputs.yml)}
    dynamoDBResources:
      Deploy: Before
      StackName: ${self:custom.dynamoDBStackName}
      Resources: ${file(./resources/dynamodb.yml)}

  appSync:
    name: ${self:service}-${self:provider.stage}-api
    authenticationType: AWS_IAM
    logConfig:
      loggingRoleArn: ${self:custom.role.logging.arn}
      level: ALL
    mappingTemplates:
      - dataSource: realtimedata
        type: Mutation
        field: refreshProgressBar
        request: "request/dynamodb/create-item-request-mapping-template.vtl"
        response: "response/generic-response-mapping-template.vtl"
      - dataSource: dyanomodbdatasource
        type: Mutation
        field: createFilemappingmaster
        request: "request/dynamodb/delete-item-request-mapping-template.vtl"
        response: "response/generic-response-mapping-template.vtl"
      - dataSource: dyanomodbdatasource
        type: Mutation
        field: updateFilemappingmaster
        request: "request/dynamodb/update-item-request-mapping-template.vtl"
        response: "response/generic-response-mapping-template.vtl"
      - dataSource: dyanomodbdatasource
        type: Mutation
        field: updateFilemappingmaster
        request: "request/dynamodb/update-item-request-mapping-template.vtl"
        response: "response/generic-response-mapping-template.vtl"
      - dataSource: getFileMapDetails
        type: Query
        field: getFileMapDetails
        request: "request/dynamodb/get-item-request-mapping-template.vtl"
        response: "response/generic-response-mapping-template.vtl"
      - dataSource: dyanomodbdatasource
        type: Query
        field: getFilemappingmaster
        request: "request/dynamodb/list-items-request-mapping-template.vtl"
        response: "response/list-items-response-mapping-template.vtl"
      - dataSource: dyanomodbdatasource
        type: Query
        field: listFilemappingmasters
        request: "request/dynamodb/get-item-request-mapping-template.vtl"
        response: "response/generic-response-mapping-template.vtl"
      - dataSource: dyanomodbdatasource
        type: Query
        field: queryFilemappingmastersBySchemeIdNameIndex
        request: "request/dynamodb/list-items-request-mapping-template.vtl"
        response: "response/list-items-response-mapping-template.vtl"
      
    mappingTemplatesLocation: "mapping-templates"
    serviceRole: AppSyncServiceRole
    dataSources:
      - type: AMAZON_DYNAMODB
        name: dyanomodbdatasource
        description: 'dyanomodbdatasource table'
        config:
          tableName: ${self:custom.db.table.note.name}
          serviceRoleArn: ${self:custom.role.dynamodb.arn}
      - type: NONE
        name: realtimedata
        description: 'realtimedata'
      - type: AWS_LAMBDA
        name: getFileMapDetails
        description: 'Lambda DataSource'
        config: # Either of functionName or lambdaFunctionArn must tbe provided. When both are present, lambdaFunctionArn is used.
          functionName: getFileMapDetail1
          lambdaFunctionArn: ${self:functions:getFileMapDetail1:arn}
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }
          

resources:
  Resources:
    AppSyncLoggingServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: ${self:custom.role.logging.name}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: ${self:custom.role.logging.name}-Policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"