service:
  name: sls-appsync-bckend-pj

plugins:
  - serverless-appsync-plugin
  - serverless-plugin-additional-stacks
  - serverless-iam-roles-per-function
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: java8
  profile: lg_sandbox # optoinal profile shold be listed in ~/.aws/credentials
  region: ${opt:region, 'us-west-2'} # optoinal
  timeout: 120
  stage: ${opt:stage, "sandbox"}

#define lambda functions here which are to be created
functions:
  listProducts:
    handler: com.serverless.ListProductsHandler
  #   events:
  #     - http:
  #         path: /products
  #         method: get

custom:
  #define service/function name and other details
  base: ${self:service}-${self:provider.stage}
  account: ${file(./config/config.${self:provider.stage}.json):account}
  lambdaStackName: ${self:custom.base}-lambda

  role:
    arn: arn:aws:iam::${self:custom.account.id}:role
    lambda:
      name: ${self:custom.base}-Lambda-AppSyncServiceRole
      arn: ${self:custom.role.arn}/${self:custom.role.lambda.name}
    logging:
      name: ${self:custom.base}-Logging-AppSyncServiceRole
      arn:
        Fn::GetAtt:
          - AppSyncLoggingServiceRole
          - Arn


# appsync function details
  appSync: ${file(./resources/Appsync.yml):appSync}
        

resources:
  Resources:
    AppSyncLoggingServiceRole:  ${file(./resources/AppSyncLoggingServiceRole.yml):AppSyncLoggingServiceRole}